version: 1
type: gradle
resolver:
  snapshotRepo: GRADLE_REPO_KEY
  releaseRepo: GRADLE_REPO_KEY
  serverID: Default-Server
deployer:
  snapshotRepo: GRADLE_REPO_KEY
  releaseRepo: GRADLE_REPO_KEY
  serverID: Default-Server
